default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: amagi123
  host: db

development:
  <<: *default
  database: casanova

# Add other environments if necessary, such as test and production.
